#!/bin/bash
# Initial setup once run through pdftotext 
# replace all weird boxes with Markdown bullets
sed -i 's//*/g' $1
# replace all  characters (idk why they show up like this) with Markdown's h2
sed -i 's//## /' $1
sed -i 's//*/g' $1
sed -i 's/▪/*/g' $1
sed -i 's/•/*/g' $1
# replace ligatures (fi), (fl) with fi, fl; this makes things easier to `grep` through
sed -i 's/ﬂ/fl/g' $1
sed -i 's/ﬁ/fi/g' $1
